version: "3.8"
services:

  # rabbitmq3:
  #     container_name: "tiktok-rabbitmq"
  #     image: rabbitmq:3.13.6-management-alpine
  #     env_file:
  #       - .env
  #     ports:
  #         # AMQP protocol port
  #         - '5674:5672'
  #         # HTTP management UI
  #         - '15674:15672'

  app:
    container_name: "employee-management-system"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    ports:
      - 6001:8000